# Generated by Django 5.2.6 on 2025-09-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okta_client', '0003_oktauser_okta_activated_oktauser_okta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oktauser',
            name='okta_created',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the account creation.', null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='oktauser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the local account was created', verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='oktauser',
            name='okta_status_changed',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last update of the "status" attribute.', null=True, verbose_name='status changed'),
        ),
    ]
