# Generated by Django 5.2.6 on 2025-09-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okta_client', '0003_oktauser_last_refresh_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oktauser',
            name='okta_id',
            field=models.CharField(blank=True, help_text='Okta internal ID for the user.', max_length=50, null=True, unique=True, verbose_name='id'),
        ),
    ]
